# This is the main configuration file for the mazizone portal.
# If you manually change some values on this file a server restart is
# mandatory for the changes to take effect.
# On the general section:
# - mode: (normal/demo) mode determines if there is an actual mazizone 
#         or this runs just for demo purposes
# On the admin section:
# - admin_username: admin username for the admin panel
# - admin_password: admin password for the admin panel.
# On the scripts section:
# - backend_scripts_folder: the folder that contains the scripts that the portal 
#                           will need to execute for various actions
# - enabled_scripts: the scripts that are allowed to be executed by the 
#                    backend (for security reasons)
# On the portal configuration section:
# - title: the title on both the top left corner and on browser title
# - applications_title: title on the applications body page
# - applications_subtitle: subtitle on the applications body page
# - applications_welcome_text: welcome text on the applications body page
# - side_panel_color: side panel main color (hex value)
# - side_panel_active_color: side panel active and on hover color (hex value)
# - top_panel_color: top panel main color (hex value)
# - side_panel_active_color: top panel active and on hover color (hex value)
---
:general:
  :mode: normal
:admin:
  :admin_username: mazi_admin
  :admin_password: '1234'
:scripts:
  :backend_scripts_folder: "/root/back-end/"
  :enabled_scripts:
  - wifiap.sh
  - current.sh
  - internet.sh
  - mazi-app.sh
  - mazi-stat.sh
  - ls
:portal_configuration:
  :title: Mazizone Portal
  :applications_title: Mazizone
  :applications_subtitle: Applications
  :applications_welcome_text: Welcome to the Mazizone Applications Portal, please
    use the links bellow to navigate to the applications offered by Mazizone.
  :side_panel_color: '222'
  :side_panel_active_color: '080808'
  :top_panel_color: '222'
  :top_panel_active_color: '080808'
